### Get All Users
GET http://localhost:8080/api/users/1 HTTP/1.1
Accept: application/json

### Create User 1
PATCH  http://localhost:8080/api/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "ilhamdidaz"
}

### Create User 2
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "john_doe",
    "email": "john.doe@example.com",
    "phoneNumber": "9876543210"
}

### Create Store 1 (Owned by User ID 1)
PUT http://localhost:8080/api/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "john_doe",
    "email": "john.doe@example.com",
    "phoneNumber": "9876543210"
}

### Create Store 2 (Owned by User ID 2)
POST http://localhost:8080/api/stores HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "storeName": "John's Fashion Hub",
    "storeDescription": "Trendy clothing and accessories",
    "userId": 3

}

### Create Product 1 (Under Store ID 1)
POST http://localhost:8080/api/products HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "productName": "Wireless Mouse",
    "price": 25.99,
    "storeId": 1

}

### Create Product 2 (Under Store ID 2)
POST http://localhost:8080/api/products HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "productName": "Leather Jacket",
    "price": 89.99,
    "storeId": 3

}

### Create Order 1 (User ID 1 buying Product ID 1)
POST http://localhost:8080/api/orders HTTP/1.1
Content-Type: application/json
Accept: application/json

{
        "userId": 1,
        "productId": 1,
    "status": "pending"
}

### Create Order 2 (User ID 2 buying Product ID 2)
POST http://localhost:8080/api/orders HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "user": {
        "userId": 3
    },
    "product": {
        "productId": 2
    },
    "status": "pending"
}

### 
POST http://localhost:8080/api/product-details HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "product": {
        "productId": 2
    }
}

###
PATCH http://localhost:8080/api/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "phoneNumber": "99999991"
}


###
PUT  http://localhost:8080/api/stores/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "storeName": "Ilham Blazingly Fast Tech Store",
    "storeDescription": "Most Cutting Edge Tech Store HAHAHA",
    "user": {
        "userId": 1
    }
}

###

PATCH http://localhost:8080/api/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email":"john897doe@gmail.com"
}


###
PATCh http://localhost:8080/api/orders/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "status": "cancelled"
}